# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imagename: 'siddharta02/sid'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'dockerhub'
    repository: $(imagename)
    command: buildAndPush
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(tag)

      
