apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: sid
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      imagePullPolicy: Always
      containers:
      - name: my-app-container
        image: siddharta02/sid:latest
        ports:
        - containerPort: 80
